# Generated by Django 4.1 on 2022-11-14 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(null=True, upload_to="profile_images"),
                ),
                (
                    "user_street",
                    models.TextField(
                        help_text="Enter street name", max_length=50, null=True
                    ),
                ),
                (
                    "user_city",
                    models.CharField(
                        help_text="Enter city name", max_length=20, null=True
                    ),
                ),
                (
                    "user_state",
                    models.CharField(
                        help_text="Enter state name", max_length=20, null=True
                    ),
                ),
                (
                    "user_zipcode",
                    models.CharField(
                        help_text="Enter zipcode name", max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "stock_name",
                    models.CharField(
                        help_text="Enter the stock name", max_length=20, null=True
                    ),
                ),
                (
                    "stock_ticker",
                    models.CharField(
                        help_text="Enter the stock ticker",
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.stock",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_percentage_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the stock threshold percentage change content",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.stock",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_title",
                    models.CharField(
                        help_text="Enter the stock news title",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "news_content",
                    models.TextField(
                        help_text="Enter the stock news content",
                        max_length=5000,
                        null=True,
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.stock",
                    ),
                ),
            ],
        ),
    ]
